/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class EventEmitter {
  usingDomains: boolean
  defaultMaxListeners: number
  addListener(name : string, listener : (...args : any[]) => void): void
  on(name : string, listener : (...args : any[]) => void): void
  emit(name : string, args : any[]): boolean
}
